version: '3'

services:
  api:
    container_name: 'api'
    build: .
    restart: always
    tty: true
    ports:
      - '8001:8000'
    volumes:
      - ./src:/usr/src/api
      - ./tools:/usr/src/tools
      - ./.env:/usr/src/.env
    environment:
      TZ: Asia/Tokyo